spring:
  datasource:
#    url: jdbc:mysql://134.175.80.233/warehouse?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost/warehouse?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  profiles:
    active: dev
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.image-path}


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.realguo.warehouse.entity
  configuration:
    map-underscore-to-camel-case: true


web:
#  image-path: D:/pic/
  image-path: /Users/bytedance/Desktop/pic

